runtime: nodejs14
instance_class: F1

# With this config, we can run 24/7 without
# paying a cent because of 28h free quota.
automatic_scaling:
  max_instances: 1
  min_instances: 1

env_variables:
  NODE_ENV: "production"
